linters:
  enable:
    - cyclop
    - decorder
    - err113
    - errcheck
    - errname
    - gci
    - goconst
    - gocritic
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - stylecheck
    - unused
